# Generated by Django 5.0.6 on 2024-05-29 22:29

# pylint: disable=invalid-name
# pylint: disable=line-too-long
"""docstring for auto-generated module"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """docstring for auto-generated class"""

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='status_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todos',
            name='task',
            field=models.CharField(max_length=50),
        ),
    ]
